public class TestObjectTriggerHandler {
    public static void doBeforeInsert(List<TestObject__c> newList) {
        
    }
    
    public static void doAfterInsert(List<TestObject__c> newList) {
        
    }
    
    public static void doBeforeUpdate(List<TestObject__c> newList, Map<Id, TestObject__c> oldMap) {
        
    }
    
    public static void doAfterUpdate(List<TestObject__c> newList, Map<Id, TestObject__c> oldMap) {
        
    }
    
    public static void doBeforeDelete(Map<Id, TestObject__c> oldMap) {
        
    }
    
    public static void doAfterDelete(Map<Id, TestObject__c> oldMap) {
        
    }
}